APPLICATION_NAME = "REPORT_CRUNCHER_SERVICE"
LOG_TIMESTAMP_FORMAT = "%Y-%m-%d %H:%M:%S"


API_ERROR_UNHANDELED = "T0000"
API_ERROR_NO_FILE_FOUND = "T0001"
API_ERROR_UNSUPPORTED_FILE_FOUND = "T0002"
API_ERROR_USER_ID_IS_MISSING = "T0003"

ACCESS_TOKEN_RETRIEVAL_MAX_RETRIES = 5
ACCESS_TOKEN_RETRIEVAL_TIMEOUT = 10


SERVER_LOG_LEVEL_ENV_KEY = "SERVER_LOG_LEVEL"
APP_LOG_LEVEL_ENV_KEY = "APP_LOG_LEVEL"

# Redis service
REDIS_API_KEY = "REDIS_API_KEY"
REDIS_HOST_KEY = "REDIS_HOST"
REDIS_PORT_KEY = "REDIS_PORT"

# OpenAI service
OPENAI_API_KEY = "OPENAI_API_KEY"

